/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleDetalhesVideo1;
import model.Filme;
import model.ListaReproducao;
import model.Serie;
import model.Usuario;
import model.Video;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author unifipinho
 */
public class DetalhesVideo1 extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalhesVideo1.class.getName());

    private ControleDetalhesVideo1 c;
    private Video video;
    private Usuario usuario;
    /**
     * Creates new form DetalhesVideo1
     */
    public DetalhesVideo1() {
        initComponents();
    }
    public void setVideo(Video video) {
        this.video = video;
        preencherDados();
        verificarSetup();
    }
 
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        verificarSetup();
    }
 
    private void verificarSetup() {
        if (video != null && usuario != null) {
            c = new ControleDetalhesVideo1(this, video, usuario);
            btnCurtir.setText(c.isCurtido() ? "Descurtir" : "Curtir");
            lblCurtidas.setText("Curtidas: " + c.contarCurtidas());
        }
    }
 
    private void preencherDados() {
        if (video == null) return;
        lblTitulo.setText("Titulo: " + video.getTitulo());
        lblTitulo2.setText("Tipo: " + video.getTipo());
        lblAno.setText("Ano: " + video.getAnoLancamento());
        txtDescricao.setText(video.getDescricao());
        txtDescricao.setEditable(false);
        txtDescricao.setLineWrap(true);
        txtDescricao.setWrapStyleWord(true);
        if (video instanceof Filme filme) {
            lblDetalhe1.setText("Duracao: " + filme.getDuracao() + " min");
        } else if (video instanceof Serie serie) {
            lblDetalhe1.setText("Temporadas: " + serie.getTemporadas());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo2 = new javax.swing.JLabel();
        lblCurtidas = new javax.swing.JLabel();
        lblDetalhe1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnCurtir = new javax.swing.JButton();
        btnFavorito = new javax.swing.JButton();
        btnAdicionarLista = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitulo2.setText("Tipo:");

        lblCurtidas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCurtidas.setText("Curtidas: 0");

        lblDetalhe1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDetalhe1.setText("Detalhes:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        btnCurtir.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurtirActionPerformed(evt);
            }
        });

        btnFavorito.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnFavorito.setText("Favoritar");
        btnFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritoActionPerformed(evt);
            }
        });

        btnAdicionarLista.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnAdicionarLista.setText("Add na Lista");
        btnAdicionarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarListaActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitulo.setText("Título:");

        lblAno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAno.setText("Ano:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDetalhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCurtir)
                        .addGap(114, 114, 114)
                        .addComponent(btnFavorito)
                        .addGap(105, 105, 105)
                        .addComponent(btnAdicionarLista)
                        .addGap(57, 57, 57))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDetalhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurtir)
                    .addComponent(btnAdicionarLista)
                    .addComponent(btnFavorito))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnVoltar)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        if (c.isCurtido()) {
            c.descurtir();
            btnCurtir.setText("Curtir");
        } else {
            c.curtir();
            btnCurtir.setText("Descurtir");
        }
        lblCurtidas.setText("Curtidas: " + c.contarCurtidas());
    }//GEN-LAST:event_btnCurtirActionPerformed

    private void btnFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritoActionPerformed
        c.adicionarFavorito();
    }//GEN-LAST:event_btnFavoritoActionPerformed

    private void btnAdicionarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarListaActionPerformed
        List<ListaReproducao> listas = c.listarListas();
        if (listas == null || listas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Voce nao tem listas criadas.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String[] nomes = listas.stream().map(ListaReproducao::getNomeLista).toArray(String[]::new);
        String escolha = (String) JOptionPane.showInputDialog(this, "Escolha uma lista:", "Adicionar a lista",
            JOptionPane.PLAIN_MESSAGE, null, nomes, nomes[0]);
        if (escolha != null) {
            int idLista = listas.stream()
            .filter(l -> l.getNomeLista().equals(escolha))
            .findFirst().get().getIdLista();
            c.adicionarNaLista(idLista);
        }
    }//GEN-LAST:event_btnAdicionarListaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetalhesVideo1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLista;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnFavorito;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCurtidas;
    private javax.swing.JLabel lblDetalhe1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
