/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleFavoritos1;
import model.Filme;
import model.Serie;
import model.Usuario;
import model.Video;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author unifipinho
 */
public class Favoritos1 extends javax.swing.JFrame {

    /**
     * Creates new form Favoritos1
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Favoritos1.class.getName());

    private ControleFavoritos1 c;
    private DefaultTableModel tableModel;
    private List<Video> videosFavoritos;
    
    public Favoritos1() {
        initComponents();
        configurarTabela();
    }
    
    public void setUsuario(Usuario usuario) {
        c = new ControleFavoritos1(this, usuario);
        carregarDados();
    }
 
    private void configurarTabela() {
        tableModel = new DefaultTableModel(
            new String[]{"Titulo", "Tipo", "Ano", "Detalhe"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        tblFavoritos.setModel(tableModel);
        tblFavoritos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
 
    private void carregarDados() {
        videosFavoritos = c.carregarFavoritos();
        tableModel.setRowCount(0);
        if (videosFavoritos != null) {
            for (Video v : videosFavoritos) {
                String detalhe;
                if (v instanceof Filme) detalhe = ((Filme) v).getDuracao() + " min";
                else if (v instanceof Serie) detalhe = ((Serie) v).getTemporadas() + " temporadas";
                else detalhe = "-";
                tableModel.addRow(new Object[]{v.getTitulo(), v.getTipo(), v.getAnoLancamento(), detalhe});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFavoritos = new javax.swing.JTable();
        btnDetalhes = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setText("Meus Favoritos");

        tblFavoritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFavoritos);

        btnDetalhes.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnDetalhes.setText("Ver detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        btnRemover.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(397, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnRemover)
                .addGap(68, 68, 68)
                .addComponent(btnDetalhes)
                .addGap(71, 71, 71)
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalhes)
                    .addComponent(btnVoltar)
                    .addComponent(btnRemover))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        int idx = tblFavoritos.getSelectedRow();
        if (idx < 0 || videosFavoritos == null || idx >= videosFavoritos.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um video.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        DetalhesVideo1 det = new DetalhesVideo1();
        det.setVideo(videosFavoritos.get(idx));
        det.setUsuario(c.getUsuario());
        det.setVisible(true);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int idx = tblFavoritos.getSelectedRow();
        if (idx < 0 || videosFavoritos == null || idx >= videosFavoritos.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um video.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        c.removerFavorito(videosFavoritos.get(idx).getIdVideo());
        carregarDados();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Favoritos1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFavoritos;
    // End of variables declaration//GEN-END:variables
}
