/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleListasReproducao1;
import model.Filme;
import model.ListaReproducao;
import model.Serie;
import model.Usuario;
import model.Video;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class ListasReproducao1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListasReproducao1.class.getName());
    /**
     * Creates new form ListasReproducao1
     */


    private ControleListasReproducao1 c;
    private DefaultTableModel modelListas;
    private DefaultTableModel modelVideos;
    private List<ListaReproducao> listas;
    private List<Video> videosLista;

    public ListasReproducao1() {
        initComponents();
        configurarTabelas();
    }    
 
    public void setUsuario(Usuario usuario) {
        c = new ControleListasReproducao1(this, usuario);
        carregarListas();
    }
 
    private void configurarTabelas() {
        modelListas = new DefaultTableModel(new String[]{"Nome da Lista"}, 0) {
            @Override public boolean isCellEditable(int r, int col) { return false; }
        };
        tblListas.setModel(modelListas);
        tblListas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) carregarVideosDaLista();
        });
 
        modelVideos = new DefaultTableModel(new String[]{"Titulo", "Tipo", "Ano", "Detalhe"}, 0) {
            @Override public boolean isCellEditable(int r, int col) { return false; }
        };
        tblVideos.setModel(modelVideos);
        tblVideos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
 
    private void carregarListas() {
        listas = c.carregarListas();
        modelListas.setRowCount(0);
        if (listas != null) {
            for (ListaReproducao l : listas) {
                modelListas.addRow(new Object[]{l.getNomeLista()});
            }
        }
        modelVideos.setRowCount(0);
    }
 
    private void carregarVideosDaLista() {
        int idx = tblListas.getSelectedRow();
        if (idx < 0 || listas == null || idx >= listas.size()) return;
        videosLista = c.carregarVideosLista(listas.get(idx).getIdLista());
        modelVideos.setRowCount(0);
        if (videosLista != null) {
            for (Video v : videosLista) {
                String detalhe;
                if (v instanceof Filme) detalhe = ((Filme) v).getDuracao() + " min";
                else if (v instanceof Serie) detalhe = ((Serie) v).getTemporadas() + " temporadas";
                else detalhe = "-";
                modelVideos.addRow(new Object[]{v.getTitulo(), v.getTipo(), v.getAnoLancamento(), detalhe});
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListas = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVideos = new javax.swing.JTable();
        btnRemoverVideo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Listas de Reprodução");

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Minhas Listas");

        tblListas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListas);

        btnExcluir.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnExcluir.setText("Excluir lista");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Vídeos da Lista:");

        tblVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVideos);

        btnRemoverVideo.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnRemoverVideo.setText("Remover Video");
        btnRemoverVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir)
                            .addComponent(btnCriar)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoverVideo)
                            .addComponent(jLabel3)
                            .addComponent(btnVoltar)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemoverVideo)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int idx = tblListas.getSelectedRow();
        if (idx < 0 || listas == null || idx >= listas.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma lista.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        c.excluirLista(listas.get(idx).getIdLista());
        carregarListas();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        String nome = javax.swing.JOptionPane.showInputDialog(this, "Nome da nova lista:", "Criar Lista", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (nome == null) return;
        c.criarLista(nome);
        carregarListas();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int idx = tblListas.getSelectedRow();
        if (idx < 0 || listas == null || idx >= listas.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma lista.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String novoNome = (String) javax.swing.JOptionPane.showInputDialog(this,
            "Novo nome:", "Editar Lista",
            javax.swing.JOptionPane.PLAIN_MESSAGE, null, null, listas.get(idx).getNomeLista());
        if (novoNome == null) return;
        c.editarLista(listas.get(idx).getIdLista(), novoNome);
        carregarListas();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverVideoActionPerformed
        int idxLista = tblListas.getSelectedRow();
        int idxVideo = tblVideos.getSelectedRow();
        if (idxLista < 0 || idxVideo < 0 || videosLista == null || idxVideo >= videosLista.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma lista e um video.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        c.removerVideoLista(listas.get(idxLista).getIdLista(), videosLista.get(idxVideo).getIdVideo());
        carregarVideosDaLista();
    }//GEN-LAST:event_btnRemoverVideoActionPerformed
                                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new ListasReproducao1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRemoverVideo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblListas;
    private javax.swing.JTable tblVideos;
    // End of variables declaration//GEN-END:variables
}
